name: orchestrator-pipeline-build
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  # Build stage
  Build:
    name: maven-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-


      - name: Extract project version and artifact ID
        run: |
            VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
            ARTIFACT_ID=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="artifactId"]/text()' pom.xml)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV    

      - name: Maven clean install
        run: mvn clean install

      - name: Cache built JAR
        uses: actions/cache@v3
        with:
          path: target/
          key: ${{ runner.os }}-jar-${{ hashFiles('target/*.jar') }}
          restore-keys: ${{ runner.os }}-jar-


  #Test:
  #name: sast/sonarqube


    #  Package:
    #   name: package spring-project

    #deploy:
    # name: kubernetes
